config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'home#index'

  namespace :admin do
    root 'home#index'
    resources :hotels do
      resources :promotions, controller: 'promotions_hotels'
    end
    resources :rooms do
      resources :promotions, controller: 'promotions_rooms'
    end
    resources :bookings
  end

  namespace :api do
    post "/login", to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    get '/me', to: 'users#me'
    resources :hotels do
      resources :promotions, controller: 'promotions_hotels'
    end
    resources :bookings
    
    resources :rooms do
      member do
        post 'book'
      end
      resources :promotions, controller: 'promotions_rooms'
    end
  end
  
  resources :hotels do
    member do
      get 'rooms'
    end    
  end

  resources :rooms  do
    member do
      post 'book'
    end
  end

  resources :bookings
end

app/models/booking.rb
class Booking < ApplicationRecord
  before_destroy :notify_users, :booking_deleted
  after_create :send_confirmation, :notify_booking, :reservation_tomorrow
  belongs_to :user
  belongs_to :room

  def notify_users
    BookingMailer.with(user: user, booking: self).notify_users.deliver_later
  end  

  def send_confirmation
    BookingMailer.with(user: user, booking: self).booking_confirmation.deliver_now
  end

  def notify_booking
    BookingMailer.with(user: user, booking: self, hotel: self.room.hotel).booking_notification.deliver_later
  end

  def booking_deleted
    BookingMailer.with(user: user, booking: self).user_booking_deleted.deliver_later
  end

  def reservation_tomorrow
    SendReminderNotificationJob.set(wait_until: ((self.start_date - 1.day)- DateTime.now).to_s).perform_later(self)
  end

end

app/controllers/admin/bookings_controller.rb
class Admin::BookingsController < ApplicationController
  before_action :authorization_method
  before_action :set_bookings, only: [:show, :edit, :update, :destroy]

  def index
    @bookings = Booking.all
  end

  def new
    @booking = Booking.new
  end

  def show
  end
  
  def edit
  end

  def create
    @booking = Booking.new(booking_params)

    if @booking.save 
      redirect_to admin_bookings_path(@booking), notice: 'Booking already created!'
    else
      render :new
    end
  end

  def update
    if @booking.update(booking_params)
      redirect_to admin_bookings_path(@booking), notice: 'Booking already updated!'
    else
      render :edit
    end
  end

  def destroy
    @booking.destroy
    redirect_to admin_bookings_path, notice: "Booking already deleted!"
  end

  private

  def set_bookings
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:paid_price, :user_id, :room_id, :start_date, :end_date)
  end

  def authorization_method
    authorize [:admin, Booking]
  end
end

app/controllers/api/bookings_controller.rb
class Api::BookingsController < ApiController
  before_action :authorization_method

  before_action :set_booking, only: [:show, :update, :destroy]
  def index
    render json: Booking.all
  end

  def show 
    render json: @booking
  end

  def create
    booking = Booking.new(booking_params)
    if booking.save
      render json: booking
    else
      render json: { message: 'Booking not saved' }, 
                      status: :unprocessable_entity
    end
  end

  def destroy
    @booking.destroy
      render json: { message: 'Booking deleted' },
                      status: :ok
  end

  def update
    if @booking.update_attributes(booking_params)
      render json: { message: 'Updated Booking'} , 
                      status: :ok
    else
      render json: { message: 'Booking not updated'} , 
                      status: :unprocessable_entity
    end
  end

  private
  def booking_params
    params.permit(:start_date,:end_date,:paid_price,:user_id,:room_id)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def authorization_method
    authorize Booking
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]
  before_action :authorization_method, except: [:create]

  def index 
    if params[:search].present?
      @bookings = Booking.where(name: params[:search])
    else
      @bookings = Booking.where(user: current_user)
    end
  end

  def show

  end

  def new
    @booking = Booking.new
  end

  def create    
    @booking = Booking.new(booking_params)
    authorize @booking

    if @booking.save(booking_params)
      redirect_to booking_path(@booking), notice: "The booking was successfully created"
    else
      render :new
    end

  end

  def edit

  end

  def update
    if @booking.update(booking_params)
      redirect_to booking_path(@booking), notice: "The booking was successfully updated"
    else
      render :edit
    end

  end

  def destroy
    @booking.destroy
    redirect_to bookings_path, notice: "The booking was successfully deleted"

  end

  private 

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :paid_price, :user_id, :room_id)
  end

  def authorization_method
    authorize Booking
  end

end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/regular/bookings/_form.html.erb
<%= form_for [:admin, @booking] do |f| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @booking.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_date %>
    <%= f.date_field :start_date %>
  </div>

  <div class="field">
    <%= f.label :end_date %>
    <%= f.date_field :end_date %>
  </div>

  <div class="field">
    <%= f.label :paid_price %>
    <%= f.number_field :paid_price %>
  </div>

  <p>User</p>
  <%= f.collection_select(:user_id, User.all, :id, :name) %>

  <p>Room</p>
  <%= f.collection_select(:room_id, Room.all, :id, :name) %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/regular/bookings/edit.html.erb
<%= render 'form', hotel: @booking %>

<%= link_to 'Back', admin_bookings_path %>

app/views/regular/bookings/index.html.erb
<div class="controls">
  <%= link_to "New Booking", new_admin_booking_path, class: "btn" %>
</div>
<% @bookings.each do |booking| %>
<div class="piece">
  <% booking.room.hotel.cover.each do |image| %>
    <%= image_tag(image.variant(resize: "200x200"), :alt => booking.room.hotel.name) %>
  <% end %>
  <div class="piece-right">
    <h2><%= link_to booking.room.hotel.name, admin_booking_path(booking) %></h2>
    <%# <h2><%= link_to booking.id, admin_booking_path(booking) %><%#</h2> %>
    <p><b>From:</b> <%= booking.start_date %></p>
    <p><b>To:</b> <%= booking.end_date %></p>
    <p><b>Paid Price:</b> US$ <%= booking.paid_price %></p>
    <p><b>Name:</b> <%= mail_to booking.user.email, booking.user.name %></p>
    <%# <p>User Email: <%= booking.user.email %><%#</p> %>
    <p><b>Room name:</b> <%= booking.room.name %></p>
    <%# <p>Hotel: <%= booking.room.hotel.name %><%#</p> %>
  </div>
</div>
<% end%>

app/views/regular/bookings/new.html.erb
<%= render 'form', hotel: @booking %>

<%= link_to 'Back', admin_bookings_path %>

app/views/regular/bookings/show.html.erb
<h2><%= @booking.id %></h2>
<p>From: <%= @booking.start_date %></p>
<p>To: <%= @booking.end_date %></p>
<p>Paid Price: <%= @booking.paid_price %></p>
<p>User Name: <%= @booking.user.name %></p>
<p>User Email: <%= @booking.user.email %></p>
<p>Room: <%= @booking.room.name %></p>
<p>Hotel: <%= @booking.room.hotel.name %></p>

<%= link_to 'Back', admin_bookings_path %>
<%= link_to "Edit", edit_admin_booking_path(@booking) %>
<%= link_to "Delete", admin_booking_path(@booking), method: :delete, data: { confirm: "Are you sure?" } %>