config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'home#index'

  namespace :admin do
    root 'home#index'
    resources :hotels do
      resources :promotions, controller: 'promotions_hotels'
    end
    resources :rooms do
      resources :promotions, controller: 'promotions_rooms'
    end
    resources :bookings
  end

  namespace :api do
    post "/login", to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    get '/me', to: 'users#me'
    resources :hotels do
      resources :promotions, controller: 'promotions_hotels'
    end
    resources :bookings
    
    resources :rooms do
      member do
        post 'book'
      end
      resources :promotions, controller: 'promotions_rooms'
    end
  end
  
  resources :hotels do
    member do
      get 'rooms'
    end    
  end

  resources :rooms  do
    member do
      post 'book'
    end
  end

  resources :bookings
end

app/views/partials/_nav.html.erb
<nav>
  <div class="navbar">
    
      <h1 class="logo"><a href="/"><span class="logo-blue">tri</span><span class="logo-yellow">va</span><span class="logo-red">go</span><span class="logo-grey">-clone</span></a></h1>
    
    <ul>
      <li><%= link_to "Hotels", admin_hotels_path %></li>
      <li><%= link_to "Rooms", admin_rooms_path %></li>
      <li><%= link_to "Bookings", admin_bookings_path %></li>
    </ul>
  </div>
</nav>

app/views/partials/_nav_admin.html.erb
<nav>
  <div class="navbar">
    
      <h1 class="logo"><a href="/admin"><span class="logo-blue">tri</span><span class="logo-yellow">va</span><span class="logo-red">go</span><span class="logo-grey">-clone</span></a></h1>
    
    <ul>
      <li><%= link_to "Hotels", admin_hotels_path %></li>
      <li><%= link_to "Rooms", admin_rooms_path %></li>
      <li><%= link_to "Bookings", admin_bookings_path %></li>
    </ul>
  </div>
</nav>

app/views/partials/_nav_regular.html.erb
<nav>
  <div class="navbar">
    
      <h1 class="logo"><a href="/"><span class="logo-blue">tri</span><span class="logo-yellow">va</span><span class="logo-red">go</span><span class="logo-grey">-clone</span></a></h1>
    
    <ul>
      <li><%= link_to "Hotels", hotels_path %></li>
      <li><%= link_to "Rooms", rooms_path %></li>
    </ul>
  </div>
</nav>