config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'home#index'

  namespace :admin do
    root 'home#index'
    resources :hotels do
      resources :promotions, controller: 'promotions_hotels'
    end
    resources :rooms do
      resources :promotions, controller: 'promotions_rooms'
    end
    resources :bookings
  end

  namespace :api do
    post "/login", to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    get '/me', to: 'users#me'
    resources :hotels do
      resources :promotions, controller: 'promotions_hotels'
    end
    resources :bookings
    
    resources :rooms do
      member do
        post 'book'
      end
      resources :promotions, controller: 'promotions_rooms'
    end
  end
  
  resources :hotels do
    member do
      get 'rooms'
    end    
  end

  resources :rooms  do
    member do
      post 'book'
    end
  end

  resources :bookings
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  has_many :rooms, dependent: :destroy
  has_many :promotions, as: :promotionable, dependent: :destroy
  has_many :bookings, through: :rooms
  has_many_attached :cover

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/ }
  validates :city, presence: true
  validates :country, presence: true
  validates :address, presence: true

  def notify_users
    BookingMailer.with(user: user, booking: room_id).notify_users.deliver_later
  end
end

app/controllers/admin/hotels_controller.rb
class Admin::HotelsController < ApplicationController
  before_action :authorization_method
  before_action :set_hotels, only: [:show, :edit, :update, :destroy]

  def index
    @hotels = Hotel.all
  end

  def new
    @hotel = Hotel.new
  end

  def show
  end
  
  def edit
  end

  def create
    @hotel = Hotel.create(hotel_params)

    if @hotel.save 
      redirect_to admin_hotel_path(@hotel), notice: 'Hotel already created!'
    else
      render :new
    end
  end

  def update
    if @hotel.update(hotel_params)
      redirect_to admin_hotel_path(@hotel), notice: 'Hotel already updated!'
    else
      render :edit
    end
  end

  def destroy
    @hotel.destroy
    redirect_to admin_hotels_path, notice: "Hotel already deleted!"
  end

  private

  def set_hotels
    @hotel = Hotel.find(params[:id])
  end

  def hotel_params
    params.require(:hotel).permit(:name, :email, :city, :country, :address, cover: [])
  end

  def authorization_method
    authorize [:admin, Hotel]
  end
end

app/controllers/api/hotels_controller.rb
class Api::HotelsController < ApiController
  before_action :authorization_method
  def index
    render json: Hotel.all
  end

  def show
    render json: Hotel.find(params[:id])
  end

  def create
    hotel = Hotel.new(hotel_params)
    if hotel.save
      render json: hotel
    else
      render json: { message: 'Hotel not saved' }, 
                      status: :unprocessable_entity
    end
  end

  def destroy
    hotel = Hotel.find(params[:id])
    hotel.destroy
      render json: { message: 'Hotel deleted'},
                      status: :ok
  end

  def update
    hotel = Hotel.find(params[:id])
    if hotel.update_attributes(hotel_params)
      render json: { message: 'Updated hotel'} , 
                      status: :ok
    else
      render json: { message: 'Hotel not updated'} , 
                      status: :unprocessable_entity
    end
  end

  private
  def hotel_params
    params.permit(:name,:email,:city,:country,:address)
  end

  def authorization_method
    authorize Hotel
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :authorization_method

  def index
    if params[:search].present?
      @hotels = Hotel.where(name: params[:search])
    else
      @hotels = Hotel.all
    end
  end

  def show
    @hotel = Hotel.find(params[:id])
  end

  def rooms
    @hotel = Hotel.find(params[:id])
    @rooms = @hotel.rooms

    if params[:min_price].present? && params[:max_price].present?
      @rooms = @rooms.where(
        'price <= ? AND price >= ?',
        params[:max_price], params[:min_price]
      )
    end

    if params[:min_beds].present? && params[:max_beds].present?
      @rooms = @rooms.where(
        'amount_of_beds <= ? AND amount_of_beds >= ?',
        params[:max_beds], 
        params[:min_beds]
      )
    end

  end

  def authorization_method
    authorize Hotel
  end

end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/admin/hotels/_form.html.erb
<%= form_for [:admin, @hotel] do |f| %>
  <% if @hotel.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @hotel.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<%# Hotel name %>
  <div class="field">
    <%= f.label :name, "Hotel name: " %>
    <%= f.text_field :name, :placeholder => "Enter Hotel name" %>
  </div>
<%# Hotel contact %>
  <div class="field">
    <%= f.label :email, "Hotel contact: " %>
    <%= f.email_field :email, :placeholder => "Enter hotel email" %>
  </div>
  <%# Hotel address %>
  <div class="field">
    <%= f.label :address, "Address: " %>
    <%= f.text_field :address, :placeholder => "Enter hotel address" %>
  </div>
<%# Hotel city %>
  <div class="field">
    <%= f.label :city, "City: " %>
    <%= f.text_field :city, :placeholder => "Enter hotel city" %>
  </div>
<%# Hotel country %>
  <div class="field">
    <%= f.label :country, "Country: " %>
    <%= f.text_field :country, :placeholder => "Enter hotel country" %>
  </div>
  <%# Hotel images %>
  <div class="field">
    <%= f.label :cover, "Pictures: " %>
    <%= f.file_field :cover, :multiple => true, :class => "btn" %>
  </div>

  <div class="actions">
    <%= f.submit "Save Hotel", :class => "btn btn-new" %>
  </div>
<% end %>

app/views/admin/hotels/edit.html.erb
<h2>Editing hotel <%= @hotel.name %></h2>
<!--<p>Find me in app/views/hotels/edit.html.erb</p>-->

<%= render 'form', hotel: @hotel %>
<div class="controls">
  <%= link_to "« Back", admin_hotels_path, :class => "btn btn-back" %>
</div>

app/views/admin/hotels/index.html.erb
<div>
  <div class="controls">
    <%= link_to "New Hotel", new_admin_hotel_path, class: "btn btn-new" %>
  </div>
</div>
<h2>List Hotels</h2>
<table>
  <thead>
    <tr>
      <th>Hotel Name</th>
      <th>Email</th>
      <th>City</th>
      <th>Country</th>
      <th>Address</th>
      <th>Promotions</th>
      <th>Picture</th>
    </tr>
  </thead>
  <tbody>
    <% @hotels.each do |hotel| %>
      <tr>
        <td><%= link_to hotel.name, admin_hotel_path(hotel) %></td>
        <td><%= mail_to hotel.email, "Contact" %></td>
        <%#<td><%= hotel.email %><%#</td> %>
        <td><%= hotel.city %></td>
        <td><%= hotel.country %></td>
        <td><%= hotel.address %></td>
        <td>
            <% if hotel.promotions.any? %>
            <%= link_to 'Available', admin_hotel_promotions_path(hotel) %>
            <% else %>
            <%= link_to 'Unavailable', admin_hotel_promotions_path(hotel) %>
            <% end %>
          </td>
        <td>
          <% if hotel.cover.attached? %>
            <% hotel.cover.each do |image| %>
              <%= image_tag(image.variant(resize: "200x200"), :alt => hotel.name) %>
            <% end %>
          <% end %>
        </td>
      <% end%>
      </tr>  
  </tbody>
</table>

app/views/admin/hotels/new.html.erb
<h2>New hotel</h2>
<!--<p>Find me in app/views/hotels/new.html.erb</p> -->

<%= render 'form', hotel: @hotel %>
<div class="controls">
  <%= link_to "« Back", admin_hotels_path, :class => "btn btn-back" %>
</div>

app/views/admin/hotels/show.html.erb
<div class="piece">
  <div>
    <h2><%= @hotel.name %></h2>
    <% if @hotel.cover.attached? %>
      <% @hotel.cover.each do |image| %>
        <%= image_tag(image.variant(resize: "200x200"), :alt => @hotel.name) %>
      <% end %>
    <% end %>
  </div>
  <div class="piece-right">
    <p><b>Contact:</b> <%= mail_to @hotel.email, "Contact" %></p>
    <p><b>City:</b> <%= @hotel.city %></p>
    <p><b>Country:</b> <%= @hotel.country %></p>
    <p><b>Address:</b> <%= @hotel.address %></p>
  </div>
</div>
<div class="controls">
  <%= link_to "« back", admin_hotels_path, :class => "btn btn-back" %>
  <%= link_to "✎ edit", edit_admin_hotel_path(@hotel), :class => "btn btn-edit" %>
  <%= link_to "🗑 delete", admin_hotel_path(@hotel), method: :delete, data: { confirm: "Do you really want to delete this hotel?" }, :class => "btn btn-delete" %>
</div>