config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'home#index'

  namespace :admin do
    root 'home#index'
    resources :hotels do
      resources :promotions, controller: 'promotions_hotels'
    end
    resources :rooms do
      resources :promotions, controller: 'promotions_rooms'
    end
    resources :bookings
  end

  namespace :api do
    post "/login", to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    get '/me', to: 'users#me'
    resources :hotels do
      resources :promotions, controller: 'promotions_hotels'
    end
    resources :bookings
    
    resources :rooms do
      member do
        post 'book'
      end
      resources :promotions, controller: 'promotions_rooms'
    end
  end
  
  resources :hotels do
    member do
      get 'rooms'
    end    
  end

  resources :rooms  do
    member do
      post 'book'
    end
  end

  resources :bookings
end

app/controllers/admin/promotions_rooms_controller.rb
class Admin::PromotionsRoomsController < ApplicationController
  before_action :authorization_method
  def index
    @room = Room.find(params[:room_id])
    @promotions = @room.promotions
  end

  def new
    @room = Room.find(params[:room_id])
    @promotion = Promotion.new
  end

  def show 
    @room = Room.find(params[:room_id])
    @promotion = Promotion.find(params[:id])
  end

  def edit 
    @room = Room.find(params[:room_id])
    @promotion = Promotion.find(params[:id])
  end

  def create
    @room = Room.find(params[:room_id])
    @promotion = @room.promotions.new(promotion_params)
    if @promotion.save
      redirect_to admin_room_promotions_path(@room), notice: 'Promotion was successfully created'
    else 
      render :new
    end
  end

  def update
    @room = Room.find(params[:room_id])
    @promotion = Promotion.find(params[:id])
    if @promotion.update(promotion_params)
      redirect_to admin_room_promotions_path(@room), notice: 'Promotion was successfully updated'
    else 
      render :new
    end
  end

  def destroy
    @room = Room.find(params[:room_id])
    @promotion = Promotion.find(params[:id])
    @promotion.destroy
    redirect_to admin_room_promotions_path, notice: "Promotion already deleted!"
  end

  private

  def promotion_params
    params.require(:promotion).permit(:start_date, :end_date, :discount_type, :discount_amount)
  end

  def authorization_method
    authorize [:admin, :promotion]
  end
end

app/controllers/api/promotions_rooms_controller.rb
class Api::PromotionsRoomsController < ApiController
  before_action :authorization_method
  before_action :set_promotion, only: [:show, :update, :destroy]
  
  def index
    render json: Room.find(params[:room_id]).promotions
  end
  
  def show
    render json: @promotion
  end
  
  def create
    room = Room.find(params[:room_id])
    promotion = room.promotions.new(promotion_params)
    if promotion.save
      render json: promotion, status: :created
    else 
      render json: { errors: @promotion.errors}
    end
  end
  
  def update
    if @promotion.update(promotion_params)
      render json: @promotion, status: :ok
    else 
      render json: { errors: @promotion.errors}
    end
  end
  
  def destroy
    @promotion.destroy
    render json: {},status: :no_content
  end
  
  rescue_from ActiveRecord::RecordNotFound do |e|
    render json: { message: e.message }, status: :not_found
  end
  
  private    
  def set_promotion
    @promotion = Promotion.find(params[:id])
  end
  
  def promotion_params
    params.permit(:start_date, :end_date, :discount_type, :discount_amount)
  end

  def authorization_method
    authorize :promotion
  end
  
end

app/views/admin/promotions_rooms/_form.html.erb
<%= form_for [:admin, @room, @promotion] do |f| %>

  <% if @promotion.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @promotion.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_date %>
    <%= f.date_field :start_date %>
  </div>

  <div class="field">
    <%= f.label :end_date %>
    <%= f.date_field :end_date %>
  </div>

  <div class="field">
    <%= f.label :discount_type %>
    <%= f.select(:discount_type, [['Fixed', 'fixed'], ['Percentage', 'percentage']]) %>
  </div>

  <div class="field">
    <%= f.label :discount_amount %>
    <%= f.number_field :discount_amount %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/promotions_rooms/edit.html.erb
<h1>Edit Promotion</h1>

<%= render 'form', promotion: @promotion %>

<%= link_to 'Back', admin_room_promotions_path(@room, @promotion) %>

app/views/admin/promotions_rooms/index.html.erb
<div>
  <h2>List Promotions of room <%= @room.name %></h2>
  <%= link_to 'Add promotion', new_admin_room_promotion_path(@room) %>
</div>

<table>
  <thead>
    <tr>
      <th>Start date</th>
      <th>End date</th>
      <th>Discount Type</th>
      <th>Discount amount</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @promotions.each do |promotion|%>
        <tr>
          <td><%= promotion.start_date %></td>
          <td><%= promotion.end_date %></td>
          <td><%= promotion.discount_type %></td>
          <td><%= promotion.discount_amount %></td>
          <td>
            <%= link_to 'Edit', edit_admin_room_promotion_path(@room, promotion) %>
            <%= link_to 'Delete', admin_room_promotion_path(@room, promotion), method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
  </tbody>
</table>

app/views/admin/promotions_rooms/new.html.erb
<h1>New Promotion</h1>

<%= render 'form', promotion: @promotion %>

<%= link_to 'Back', admin_room_promotions_path(@room, @promotion) %>

app/views/admin/promotions_rooms/show.html.erb
<div>
  <p><b>Start date:</b> <%= @promotion.start_date %></p>
  <p><b>End date:</b> <%= @promotion.end_date%></p>
  <p><b>Discount Type:</b> <%= @promotion.discount_type %></p>
  <p><b>Discount amount:</b> <%= @promotion.discount_amount %></p>
</div>

<%= link_to 'Back', admin_room_promotions_path(@room, @promotion) %>